title: Zina Kurian # your name (or website title) here
logo: "/images/JHU.png?raw=true" # your photo (or logo) here
background-color: #fff
description: > # your text below (remove <br> elements if you don't need line breaks)
  <h5>My Professional Portfolio </h5>
  <br>
  Medical Device Engineer
 <h4> <a href = "/personal">More About Me</a></h4>
  
  <br>
  <a href = "mailto: zinakurian@gmail.com">zinakurian@gmail.com</a>
  <br>
  <a href = "mailto: zkurian2@jhu.edu">zkurian2@jhu.edu</a>
  <br>
  <a href="https://twitter.com/letsmapit" class="twitter-follow-button" data-show-count="false">Follow @letsmapit</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
  
  
  <br>
  <a href="https://www.linkedin.com/in/zinakurian">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
