title: Zina Kurian Portfolio 
logo: "/images/JHU.png?raw=true width =100" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  My Professional Portfolio 
  <br>
  Medical Device Engineer
 <a href = "/personal">More About Me</a>
  
  <br>
  <a href = "mailto: zinakurian@gmail.com">zinakurian@gmail.com</a>
  <br>
  <a href = "mailto: zkurian2@jhu.edu">zkurian2@jhu.edu</a>
  <br>
  <a href="https://twitter.com/letsmapit" class="twitter-follow-button" data-show-count="false">Follow @letsmapit</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
  
  
  <br>
  <a href="https://www.linkedin.com/in/zinakurian">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
